### ISSUE TITLE
Remarques étape 4

### ISSUE THREAD

**Issue by tentacode** [tentacode-classroom/postgresql_-2018-05-07-nicolas-julien#1]
* Json dans un dossier /ressources (en gitignore)
* mv au lieu de cp dans import
* head pour afficher du json
* ajouter les `REFERENCES` sur actor_id et repository_id
* remplacer watch_events par issue_events (issue_title, comment_count, action)
* pour push_events supprimer id, ajouter branch_name, commit_count
* INSERT INTO sur toutes les tables.
* SELECT sur toutes les tables

**Comment by neerfix** [comment]
- **[✓]** Json dans un dossier /ressources (en gitignore)
- **[✓]** mv au lieu de cp dans import
- **[✓]** head pour afficher du json
- **[✓]** ajouter les REFERENCES sur actor_id et repository_id
- **[✓]** remplacer watch_events par issue_events (issue_title, comment_count, action)
- **[✓]** pour push_events supprimer id, ajouter branch_name, commit_count
- **[✓]** INSERT INTO sur toutes les tables.
- **[✓]** SELECT sur toutes les tables
